version: "3.8"
services:
  auth-api:
    build: .
    ports:
      - "5000:5000"
    links:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:6.0.10"
    ports:
      - "6379:6379"
